# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Rails CI/CD"
on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  pull_request:
    types: [opened, reopened]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      - name: Security audit dependencies
        run: bundle exec bundle audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
